spring:
  datasource:
    url: jdbc:mysql://192.168.31.222:3306/spring-boot-core
    username: hungnq
    password: hungnq1122
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        metadata_builder_contributor: vn.amisoft.dao.SqlFunctionMetadataBuilderContributor
app:
  jwtExpirationMs: 3600000
